# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c93c5c8420870d405f47a085d3e6f8df6c32890958aa0f69f85b8c5ff1f2a3eae663bbc43b8e507be6ce8566b48283ad6ba523aa5c3ef0e1a854a32262dcd19

test:
  secret_key_base: 50e7c53b395c8a2b30182e7c22bb72469be083ea175843fe4a31cbfb6f0a76648e1ff2681af311220ff1b608995bbca5c160023c781852dba89d4b3fad3dd71f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
